// All site images live in /public/assets (served at /assets/...).
// Images marked "stock" in the original list came from GoDaddy's stock library, which is
// licensed for GoDaddy-hosted sites — replace them with photos you own or license.

export const img = {
  logo: "/assets/logo.webp",
  heroBuildings: "/assets/heroBuildings.jpg",
  whoWeAre: "/assets/whoWeAre.jpg",
  capitol: "/assets/capitol.webp",
  healthcare: "/assets/healthcare.webp",
  transaction: "/assets/transaction.webp",
  help1: "/assets/help1.webp",
  help2: "/assets/help2.webp",
  help3: "/assets/help3.webp",
  help4: "/assets/help4.webp",
  help5: "/assets/help5.webp",
  help6: "/assets/help6.webp",
  riskAssurance: "/assets/riskAssurance.webp",
  emergencyCircle: "/assets/emergencyCircle.webp",
  transactionCircle: "/assets/transactionCircle.webp",
  accountingCircle: "/assets/accountingCircle.webp",
  govColumns: "/assets/govColumns.webp",
  finance: "/assets/finance.webp",
  corps: "/assets/corps.webp",
  about1: "/assets/about1.webp",
  about2: "/assets/about2.webp",
  about3: "/assets/about3.webp",
  contact: "/assets/contact.jpg",
  healthcareBanner: "/assets/healthcareBanner.jpg",
  financialBanner: "/assets/financialBanner.jpg",
  riskBanner: "/assets/riskBanner.jpg",
  emergencyBanner: "/assets/emergencyBanner.webp",
  dealBanner: "/assets/dealBanner.webp",
  winners: "/assets/winners.webp",
  dr0: "/assets/dr0.webp",
  dr1: "/assets/dr1.webp",
  dr2: "/assets/dr2.webp",
  dr3: "/assets/dr3.webp",
  dr4: "/assets/dr4.webp",
  dr5: "/assets/dr5.webp",
};
